list.Add("NPCUsableWeapons", {class = "swep_ai_halo_ar", title = "[NPCW] HALO ASSAULT RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_br", title = "[NPCW] HALO BATTLE RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_bruteshot", title = "[NPCW] HALO BRUTESHOT"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_carbine", title = "[NPCW] HALO CARBINE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_dmr", title = "[NPCW] HALO DMR"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_magnum", title = "[NPCW] HALO MAGNUM"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_needle_rifle", title = "[NPCW] HALO NEEDLE RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_needler", title = "[NPCW] HALO NEEDLER"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_rocket_launcher", title = "[NPCW] HALO ROCKET LAUNCHER"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_shotgun", title = "[NPCW] HALO SHOTGUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_smg", title = "[NPCW] HALO SMG"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_sniper_rifle", title = "[NPCW] HALO SNIPER RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_halo_spiker", title = "[NPCW] HALO SPIKER"})

list.Add("NPCUsableWeapons", {class = "swep_ai_random_halo_unsc", title = "[NPCW] [RANDOM] HALO UNSC"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_halo_covenant", title = "[NPCW] [RANDOM] HALO COVENANT"})